name: mt-autooptimize
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyyaml
  - requests
  - pip:
      - openai
      - langchain
      - langchain-openai
      - tenacity
      - rich
